-- Seed all 80 AI/ML companies
-- Run this in Supabase SQL Editor after creating the schema

INSERT INTO companies (name, ats_type, ats_id, careers_url) VALUES
('OpenAI', 'greenhouse', 'openai', 'https://openai.com/careers'),
('Anthropic', 'greenhouse', 'anthropic', 'https://anthropic.com/careers'),
('Stability AI', 'greenhouse', 'stability-ai', 'https://stability.ai/careers'),
('Scale AI', 'greenhouse', 'scaleai', 'https://scale.com/careers'),
('Pinecone', 'greenhouse', 'pinecone', 'https://pinecone.io/careers'),
('Lightning AI', 'greenhouse', 'lightning-ai', 'https://lightning.ai/careers'),
('Deepgram', 'greenhouse', 'deepgram', 'https://deepgram.com/careers'),
('AssemblyAI', 'greenhouse', 'assemblyai', 'https://assemblyai.com/careers'),
('Synthesia', 'greenhouse', 'synthesia', 'https://synthesia.io/careers'),
('Runway', 'greenhouse', 'runway', 'https://runwayml.com/careers'),
('Comet ML', 'greenhouse', 'comet-ml', 'https://comet.com/careers'),
('Arize AI', 'greenhouse', 'arize-ai', 'https://arize.com/careers'),
('WhyLabs', 'greenhouse', 'whylabs', 'https://whylabs.ai/careers'),
('Fiddler AI', 'greenhouse', 'fiddler-ai', 'https://fiddler.ai/careers'),
('Snorkel AI', 'greenhouse', 'snorkel-ai', 'https://snorkel.ai/careers'),
('Labelbox', 'greenhouse', 'labelbox', 'https://labelbox.com/careers'),
('DataRobot', 'greenhouse', 'datarobot', 'https://datarobot.com/careers'),
('H2O.ai', 'greenhouse', 'h2oai', 'https://h2o.ai/careers'),
('C3.ai', 'greenhouse', 'c3-ai', 'https://c3.ai/careers'),
('Applied Intuition', 'greenhouse', 'applied-intuition', 'https://appliedintuition.com/careers'),
('Shield AI', 'greenhouse', 'shield-ai', 'https://shield.ai/careers'),
('Clarifai', 'greenhouse', 'clarifai', 'https://clarifai.com/careers'),
('Databricks', 'greenhouse', 'databricks', 'https://databricks.com/careers'),
('Snowflake', 'greenhouse', 'snowflake', 'https://snowflake.com/careers'),
('Glean', 'greenhouse', 'glean', 'https://glean.com/careers'),
('Moveworks', 'greenhouse', 'moveworks', 'https://moveworks.com/careers'),
('Writer', 'greenhouse', 'writer', 'https://writer.com/careers'),
('Jasper', 'greenhouse', 'jasper-ai', 'https://jasper.ai/careers'),
('Nuro', 'greenhouse', 'nuro', 'https://nuro.ai/careers'),
('Sarcos', 'greenhouse', 'sarcos', 'https://sarcos.com/careers'),
('Domino Data Lab', 'greenhouse', 'domino-data-lab', 'https://domino.ai/careers'),
('Cloudera', 'greenhouse', 'cloudera', 'https://cloudera.com/careers'),
('Midjourney', 'greenhouse', 'midjourney', 'https://midjourney.com/careers'),
('Adept AI', 'greenhouse', 'adept-ai', 'https://adept.ai/careers'),
('Inflection AI', 'greenhouse', 'inflection-ai', 'https://inflection.ai/careers'),
('Character AI', 'greenhouse', 'character-ai', 'https://character.ai/careers'),
('Aisera', 'greenhouse', 'aisera', 'https://aisera.com/careers'),
('Deci AI', 'greenhouse', 'deci-ai', 'https://deci.ai/careers'),
('Cohere', 'lever', 'cohere', 'https://cohere.com/careers'),
('Mistral AI', 'lever', 'mistral', 'https://mistral.ai/careers'),
('Hugging Face', 'lever', 'hugging-face', 'https://huggingface.co/jobs'),
('Weights & Biases', 'lever', 'wandb', 'https://wandb.ai/careers'),
('Landing AI', 'lever', 'landing-ai', 'https://landing.ai/careers'),
('Gretel AI', 'lever', 'gretel-ai', 'https://gretel.ai/careers'),
('Mostly AI', 'lever', 'mostly-ai', 'https://mostly.ai/careers'),
('Tractable', 'lever', 'tractable', 'https://tractable.ai/careers'),
('Cognite', 'lever', 'cognite', 'https://cognite.com/careers'),
('Palantir', 'lever', 'palantir', 'https://palantir.com/careers'),
('Dataiku', 'lever', 'dataiku', 'https://dataiku.com/careers'),
('Copy.ai', 'lever', 'copyai', 'https://copy.ai/careers'),
('Vercel', 'lever', 'vercel', 'https://vercel.com/careers'),
('Vespa', 'lever', 'vespa', 'https://vespa.ai/careers'),
('You.com', 'lever', 'you-com', 'https://you.com/careers'),
('Leena AI', 'lever', 'leena-ai', 'https://leena.ai/careers'),
('Wayve', 'lever', 'wayve', 'https://wayve.ai/careers'),
('Syntheticus', 'lever', 'syntheticus', 'https://syntheticus.ai/careers'),
('LangChain', 'ashby', 'langchain', 'https://langchain.com/careers'),
('Weaviate', 'ashby', 'weaviate', 'https://weaviate.io/careers'),
('Qdrant', 'ashby', 'qdrant', 'https://qdrant.tech/careers'),
('Together AI', 'ashby', 'together-ai', 'https://together.ai/careers'),
('Replicate', 'ashby', 'replicate', 'https://replicate.com/careers'),
('Modal', 'ashby', 'modal-labs', 'https://modal.com/careers'),
('ElevenLabs', 'ashby', 'elevenlabs', 'https://elevenlabs.io/careers'),
('Pika Labs', 'ashby', 'pika', 'https://pika.art/careers'),
('Perplexity AI', 'ashby', 'perplexity-ai', 'https://perplexity.ai/careers'),
('Exa AI', 'ashby', 'exa', 'https://exa.ai/careers'),
('Jina AI', 'ashby', 'jina-ai', 'https://jina.ai/careers'),
('Roboflow', 'ashby', 'roboflow', 'https://roboflow.com/careers'),
('Typeface', 'ashby', 'typeface', 'https://typeface.ai/careers'),
('Tome', 'ashby', 'tome', 'https://tome.app/careers'),
('Gamma', 'ashby', 'gamma', 'https://gamma.app/careers'),
('Mem', 'ashby', 'mem', 'https://mem.ai/careers'),
('Linear', 'ashby', 'linear', 'https://linear.app/careers'),
('Evidently AI', 'ashby', 'evidently-ai', 'https://evidentlyai.com/careers'),
('Neptune AI', 'ashby', 'neptune-ai', 'https://neptune.ai/careers'),
('RunPod', 'ashby', 'runpod', 'https://runpod.io/careers'),
('Chroma', 'ashby', 'chroma', 'https://trychroma.com/careers'),
('Luma AI', 'ashby', 'luma-ai', 'https://lumalabs.ai/careers'),
('Comma AI', 'ashby', 'comma-ai', 'https://comma.ai/careers'),
('Viso Suite', 'ashby', 'viso-suite', 'https://viso.ai/careers')
ON CONFLICT (ats_type, ats_id) DO NOTHING;
